name: Trello FU3 Email

on:
  workflow_dispatch:
  schedule:
    # 08:55 GMT+2 → 06:55 UTC
    - cron: "55 6 * * 1-5"
    # 16:55 GMT+2 → 14:55 UTC
    - cron: "55 14 * * 1-5"

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  send-fu3:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      PYTHONUNBUFFERED: "1"

      # Trello
      TRELLO_KEY:         ${{ secrets.TRELLO_KEY }}
      TRELLO_TOKEN:       ${{ secrets.TRELLO_TOKEN }}
      TRELLO_LIST_ID_FU3: ${{ secrets.TRELLO_LIST_ID_FU3 }}

      # SMTP (same pattern as Day0 / FU1 / FU2 after your fix)
      SMTP_USER:  ${{ secrets.SMTP_USER }}
      SMTP_PASS:  ${{ secrets.SMTP_PASS }}
      SMTP_HOST:  ${{ secrets.SMTP_HOST }}
      SMTP_PORT:  ${{ secrets.SMTP_PORT }}
      SMTP_USE_TLS: "1"
      SMTP_DEBUG:  "1"

      FROM_NAME:  ${{ secrets.FROM_NAME }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}

      # Links
      PUBLIC_BASE:   ${{ secrets.PUBLIC_BASE }}        # e.g. https://matlycreative.com
      PORTFOLIO_URL: ${{ secrets.PORTFOLIO_URL }}     # optional; leave empty to use PUBLIC_BASE/portfolio
      LINK_TEXT: "My portfolio"
      LINK_COLOR: "#858585"

      # Signature / BCC (optional)
      SIGNATURE_LOGO_URL: ${{ secrets.SIGNATURE_LOGO_URL }}
      BCC_TO: ${{ secrets.BCC_TO }}

      # Link rendering
      INCLUDE_PLAIN_URL: "0"

      # Marker/cache
      SENT_MARKER_TEXT: "Sent: FU3"
      SENT_CACHE_FILE:  ".data/sent_fu3.json"

    steps:
      - uses: actions/checkout@v4

      - name: Ensure data dir
        run: mkdir -p .data

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Debug env
        run: |
          echo "PUBLIC_BASE=${PUBLIC_BASE}"
          echo "PORTFOLIO_URL=${PORTFOLIO_URL}"
          echo "TRELLO_LIST_ID_FU3=${TRELLO_LIST_ID_FU3}"
          echo "FROM_EMAIL=${FROM_EMAIL}"

      - name: Run FU3 sender
        run: python trello_email_fu3.py
